# Generated by Django 6.0.4 on 2026-04-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('progress', 'В процессе'), ('done', 'Завершена')], default='new', max_length=20),
        ),
    ]
