# Generated by Django 6.0.4 on 2026-04-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
    ]
