# Generated by Django 6.0.4 on 2026-04-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_entry_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time_limit',
            field=models.DateTimeField(default=0),
        ),
    ]
