# Generated by Django 6.0.4 on 2026-04-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_alter_entry_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='time_limit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
