# Generated by Django 6.0.4 on 2026-04-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='id_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
