# Generated by Django 6.0.4 on 2026-04-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_entry_id_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='id_deleted',
            new_name='is_deleted',
        ),
    ]
